qodana:
  image:
    name: jetbrains/qodana-python-community
    entrypoint: [""]
  cache:
    - key: qodana-2024.1-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2024.1-$CI_DEFAULT_BRANCH-
        - qodana-2024.1-
      paths:
        - .qodana/cache
    - key: pyenv-cache
      paths:
        - /root/.pyenv/versions/ # cache the installed Python versions
  variables:
    QODANA_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  script:
    - apt-get update && apt-get install -y curl git gcc make build-essential
    - curl https://pyenv.run | bash
    - export PATH="/root/.pyenv/bin:$PATH"
    - eval "$(pyenv init --path)"
    - eval "$(pyenv init -)"
    - pyenv install --skip-existing 3.9.15 # Skip installation if already cached
    - pyenv global 3.9.15
    - qodana --baseline .qodana/qodana.sarif.json --cache-dir=$CI_PROJECT_DIR/.qodana/cache
  rules:
    - if: '$CI_PROJECT_PATH == "monarch-robotics/best-lowg/best-lowg"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
