qodana:
  image:
    name: jetbrains/qodana-python:2024.1
    entrypoint: [ "" ]
  cache:
    - key: qodana-2024.1-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2024.1-$CI_DEFAULT_BRANCH-
        - qodana-2024.1-
      paths:
        - .qodana/cache
  variables:
    QODANA_TOKEN: $QODANA_TOKEN
    QODANA_ENDPOINT: "https://qodana.cloud"
  script:
    - rm -rf .qodana/cache  # Clear previous Qodana cache to avoid stale issues
    - qodana --baseline .qodana/qodana.sarif.json --cache-dir=$CI_PROJECT_DIR/.qodana/cache
  rules:
    - if: '$CI_PROJECT_PATH == "monarch-robotics/best-lowg/best-lowg"'
      when: always
