qodana:
  image:
    name: jetbrains/qodana-python-community
    entrypoint: [""]
  cache:
    - key: qodana-2024.1-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2024.1-$CI_DEFAULT_BRANCH-
        - qodana-2024.1-
      paths:
        - .qodana/cache
  variables:
    QODANA_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoiQWxybDEiLCJvcmdhbml6YXRpb24iOiJBUlowTCIsInRva2VuIjoiQUc4bHIifQ.0jQVDRTIxnzNin-vQ25U3Z3562UquqyXUJhF-pj713Y
  script:
    - qodana --baseline .qodana/qodana.sarif.json --cache-dir=$CI_PROJECT_DIR/.qodana/cache
  rules:
    - if: '$CI_PROJECT_PATH == "monarch-robotics/best-lowg/best-lowg"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
