name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # Pull and run the Qodana Docker container manually with root privileges
      - name: Run Qodana Docker and Install Python 3.9
        run: |
          docker run --privileged -d --name qodana-container jetbrains/qodana-python:2024.1
          docker exec qodana-container apt-get update
          docker exec qodana-container apt-get install -y python3.9
          docker exec qodana-container python3.9 --version

      # Run the Qodana scan after Python 3.9 is installed
      - name: Qodana Scan
        run: |
          docker exec qodana-container qodana scan --cache-dir /home/runner/work/_temp/qodana/caches --results-dir /home/runner/work/_temp/qodana/results --skip-pull
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1408482145 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

      # Stop and clean up the Docker container
      - name: Clean up Docker container
        run: |
          docker stop qodana-container
          docker rm qodana-container
